***Numpy***

In [1]:
import numpy as np

In [2]:
c=np.array([1,2,3])
d=np.array([2,4,5])

In [3]:
print(c+d)
print(c-d)
print(c*d)
print(c/d)
print(c//d)
print(c%d)
print(c**d)

[3 6 8]
[-1 -2 -2]
[ 2  8 15]
[0.5 0.5 0.6]
[0 0 0]
[1 2 3]
[  1  16 243]


In [4]:
a=np.array([[1,2,3],[2,3,4]])
b=np.array([[2,3,4],[3,4,6]])

In [5]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[[ 3  5  7]
 [ 5  7 10]]
[[-1 -1 -1]
 [-1 -1 -2]]
[[ 2  6 12]
 [ 6 12 24]]
[[0.5        0.66666667 0.75      ]
 [0.66666667 0.75       0.66666667]]
[[0 0 0]
 [0 0 0]]
[[1 2 3]
 [2 3 4]]
[[   1    8   81]
 [   8   81 4096]]


#as matrix multiplication is wrong so we use transpose and keyword "dot"

In [6]:
np.dot(a,(np.transpose(b)))

array([[20, 29],
       [29, 42]])

***1. write a program to find Fibonacci series***

In [3]:
n = int(input("Enter the maximum value for the Fibonacci series: "))
a = 0
b = 1
print("Fibonacci series up to", n, ":")
while a <= n:
    print(a, end=" ")
    a, b = b, a + b

Fibonacci series up to 5 :
0 1 1 2 3 5 

***2. write a program to evaluate a string whether its palindrome or not***

In [8]:
string=input("write your string:")
if string==string[::-1]:
    print("string is pallindrome")
else:
    print("string not pallindrome")

write your string: NAMAN


string is pallindrome


***3. write a program to calculate the gross income of a family***

In [15]:
salary_1=int(input("Enter salary of person1: "))
salary_2=int(input("Enter salary of person2: "))
salary_3=int(input("Enter salary of person3: "))
tax=int(input("Enter tax amount: "))
expenses= int(input("Enter total expenses: "))
gross_income =salary_1+salary_2+salary_3
net_income =gross_income-tax-expenses
print("Gross Income:", gross_income)  #overall income that came
print("Net Income:", net_income)   #income left after necessary expenses

Enter salary of person1:  10000
Enter salary of person2:  200000
Enter salary of person3:  15000
Enter tax amount:  50000
Enter total expenses:  37000


Gross Income: 225000
Net Income: 138000


***4. write a program to make a calculator(keeps going until stopped)***

In [14]:
continuation="y"
while continuation=="y":
    a=int(input("enter first number:"))
    b=int(input("enter second number:"))
    operation=input("enter the operation you want to perform(+,-,*,/):")
    if operation=="+":
        print("Result:", a + b)
    elif operation == "-":
        print("Result:", a - b)
    elif operation == "*":
        print("Result:", a * b)
    elif operation == "/":
        if b == 0:
            print("Invalid input: Cannot divide by zero.")
        else:
            print("Result:", a / b)
    else:
        print("invalid operation entered")
    continuation = input("enter y to continue, or any other key to exit: ")

enter first number: 1
enter second number: 2
enter the operation you want to perform(+,-,*,/): +


Result: 3


enter y to continue, or any other key to exit:  y
enter first number: 1
enter second number: 6
enter the operation you want to perform(+,-,*,/): *


Result: 6


enter y to continue, or any other key to exit:  n
